name: Acceso a la fortaleza prohibida

on: push

jobs:
    reporte-de-reclutamiento:
        runs-on: ubuntu-latest

        steps:
            - name: El agente llega a la fortaleza
              run: |
                echo "Agente ${{ github.actor }} llega a la fortaleza"
                echo ""
                echo "Buscar los archivos de la legión"
                ls -la
                echo ""
                echo "❌ Pero qué pasó? No hay nada"